version: '2'
services:
    curriculumweb-app:
        image: curriculumweb
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://curriculumweb-mariadb:3306/curriculumweb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    curriculumweb-mariadb:
        extends:
            file: mariadb.yml
            service: curriculumweb-mariadb
